version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ai-agent-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ai_agents
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql